# NOTE: this file will be overwritten by dev-env.sh/utils.sh if provisioning is disabled
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# This refers to "test" by means of kustomization.yaml within ping-cloud
- ../../k8s-configs/ping-cloud/base/pingfederate/provisioning