# NOTE: image and postgres version will need to updated manually according to support in the
# postgres-operator-examples repo: https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/postgres/postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pf-provisioning
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-0
  postgresVersion: 14
  metadata:
    labels:
      role: pf-provisioning
  instances:
    - name: instance1
      replicas: 2
      minAvailable: 1
      dataVolumeClaimSpec:
        storageClassName: pgo-gp2
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            # TODO: higher default to be addressed by PDO-3866
            storage: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - pf-provisioning
                topologyKey: "failure-domain.beta.kubernetes.io/zone"
  users:
    # Service account used by PingFederate
    - name: pf-service
      databases:
        - pf-provisioning
    # Account used by Ping Beluga Ops team
    - name: ping-beluga-ops
      databases:
        - pf-provisioning
      options: "SUPERUSER"
  # TODO: Currently, backups go to a separate PVC, this will be fixed in the future to go to S3 with PDO-3863
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: pgo-gp2
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                # TODO: higher default to be addressed by PDO-3866
                storage: 1Gi
