# Delete the CloudWatch DaemonSet to reduce costs in dev CDEs - comment out to enable if required for testing
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
$patch: delete
