kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app: ping-cloud

resources:
- statefulset.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- disruption-budget.yaml
- ff-radius-proxy
- ff-provisioning

patchesStrategicMerge:
- ff-radius-proxy/pingfederate-radsecproxy.yaml
