### Feature flag - Uncomment this file to enable Postgres Operator (PGO) monitoring

# kind: Component
# apiVersion: kustomize.config.k8s.io/v1alpha1

# components:
# - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/monitoring/pgo?ref=${K8S_GIT_BRANCH}

# configMapGenerator:
#   - name: prom-alerts
#     behavior: merge
#     files:
#       - custom-alerts.yml