# p1as-cluster-tools prod settings

# ingress-nginx-public values
ingress-nginx-public:
  ingress-nginx:
    controller:
      autoscaling:
        minReplicas: 4
        maxReplicas: 6
        targetCPUUtilizationPercentage: 40
      config:
        # prod config settings
        # migrated from PCB/k8s-configs/cluster-tools/prod/small/ingress/nginx
        #
        # We will be overriding these configmap settings for existing non-small customer environments automatically in PDO-9756
        # and re-evaluating them for all environments in PDO-9757
        keep-alive-requests: "100000"
        upstream-keepalive-timeout: "30"

# Karpenter
karpenterController:
  # GA NodePool settings
  # Copied from ping-cloud-base/k8s-configs/cluster-tools/prod/large/karpenter/ga/kustomization.yaml.old
  p1asNodePools:
    enabled: true
    default:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: In
          values: ["7"]
    pdOnly:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["r"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: In
          values: ["7"]
  # GA EC2NodeClass settings
  p1asEC2NodeClass:
    default:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 120Gi
            volumeType: gp3
            encrypted: true
    pdOnly:
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 120Gi
            volumeType: gp3
            encrypted: true
  
