# p1as-cluster-tools values

global:
  karpenterEnabled: true

# ingress-nginx-public values
ingress-nginx-public:
  ingress-nginx:
    serviceAccount:
      annotations:
        ${IRSA_INGRESS_ANNOTATION_KEY_VALUE}
    controller:
      autoscaling:
        minReplicas: 3
        maxReplicas: 3
        targetCPUUtilizationPercentage: 70
      service:
        annotations:
          ${NLB_NGX_PUBLIC_ANNOTATION_KEY_VALUE}
          
ingress-nginx-private:
# ingress-nginx-private values
  ingress-nginx:
    controller:
      autoscaling:
        minReplicas: 1
        maxReplicas: 1
        targetCPUUtilizationPercentage: 70


# Karpenter configuration
karpenter:
  # Controller settings
  karpenter-controller:
    fullnameOverride: karpenter
    settings:
      clusterName: ${CLUSTER_NAME}
    serviceAccount:
      # name: "karpenter-shauntest"
      annotations:
        # eks.amazonaws.com/role-arn: "arn:aws:iam::705370621539:role/shaunmills-primary-KarpenterControllerRole"
        ${KARPENTER_ROLE_ANNOTATION_KEY_VALUE}
  # Node pool configurations
  nodePools:
    default:
  # Ec2NodeClass definitions
  ec2NodeClass:
    instanceProfile: "shaunmills-primary-KarpenterInstanceProfile"
