# NOTE: unlike the rest of this directory, this file is managed by Ping
# The rest of this directory is a direct copy of https://github.com/CrunchyData/postgres-operator-examples
# TODO: potentially fork so not in repo??
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  # TODO: just the default PGO namespace for now
  - namespace
  - default