roles: kube
authToken: ""
proxyAddr: teleport.auth.forgeblocks.com:443
kubeClusterName: "${TENANT_NAME}-${ENV}-${REGION_NICK_NAME}"
labels:
    teleport.internal/resource-id: ${TELEPORT_RESOURCE_ID}
    platform: as
    region: ${REGION_NICK_NAME}
    env: ${ENV}
    customer: ${TENANT_NAME}
    # Grab only stage portion (e.g. "ga") - prefix before first hyphen
    stage: ${STAGE%%-*}
enterprise: true