# Patch to add logging
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # Set the logging level. One of: debug|info|warn|error (default "info")
  controller.log.level: "warn"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  server.log.level: "warn"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  reposerver.log.level: "warn"
---
# Patch to update.... TODO add
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.image-updater: apiKey
  accounts.config-team: apiKey,login
  configManagementPlugins: |
    - name: git-ops-command
      generate:
        command: [ "git-ops-command.sh" ]
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
#---
# # TODO: add desc
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-rbac-cm
# data:
#   policy.csv: |
#     p, config-team, applications, action/apps/StatefulSet/restart, *, allow
#   policy.default: role:readonly
