kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- config
- admin
- engine
# Provisioning, while added here, is automatically removed from the files that reference this kustomization.yaml,
# if set to false by the environment variable PF_PROVISIONING_ENABLED
- provisioning